markdown_extensions:
  - attr_list
site_name: School Mentor Dashboard
theme: readthedocs
docs_dir: 'docs'
nav:
    - 'Home': 'index.md'
    - 'Navigation':
        - 'Accessing the Mentor Dashboard': 'sub/navigation/access.md'
        - 'Inside the Dashboard': 'sub/navigation/inside.md'
    - 'Check Solutions':
        - 'The Landing Page': 'sub/check/landing.md'
        - 'The Left Panel': 'sub/check/leftpanel.md'
        - 'Filtering the View': 'sub/check/filter.md'
        - 'The Checking Interface': 'sub/check/checkinginterface.md'
    - 'My Communities':
        - 'The All Tab': 'sub/mycomm/all.md'
        - 'The Older Than 24 Hours Tab': 'sub/mycomm/older24hr.md'
    - 'My Checking History':
        - 'Checking History List': 'sub/myhistory/list.md'
        - 'Reviewing a Checked Solution': 'sub/myhistory/historysol.md'
    - 'Challenge Config':
        - 'Challenge Config Tab': 'sub/clgconfig/list.md'
        - 'Dashboard Category Config Tab': 'sub/clgconfig/catconfig.md'
    - 'Audit Feedback':
        - 'Audit Feedback List': 'sub/audit/list.md'
        - 'Audit Solution': 'sub/audit/sol.md'
extra_css:
    - css/doc.css
